### ISSUE TITLE
Show Language server status in problems if state of language server cause compile to fail

### ISSUE THREAD

**Issue by ccecvb** [vscode-abl/vscode-abl#163] opened 2024-07-19 05:57 UTC
Currently if there is a problem with the Language server, problems for a source are not shown.

I think it would be useful if, after compile or compile buffer, problems would shown something like

`ABL Language server problem, check OUTPUT -> ABL Language server `

**Comment by gquerret** [comment] 2024-07-21 06:39
Just to be sure, what was the problem that the LS had ?

**Comment by ccecvb** [comment] 2024-07-21 15:32
It happened on VsCode on linux.

Failed to compile, probably because of previous backend processes that were still present.
Restarting ABL language server did not fix the situation.
We needed to kill the vscode process to get past it. 

Unfortunately, I did not collect the log at that time.

**Comment by gquerret** [comment] 2024-07-21 16:24
Then I'll close as duplicate of an internal ticket. The aim is to provide better feedback of the LS initialization status (in the status bar, probably with background colors, or icons)

**Closed** 2024-07-21 16:24 UTC
Labels: enhancement, Language Server

**Comment by ccecvb** [comment] 2024-07-22 06:57
@gquerret FWIW the message we got in the language server log was "Builder already started"
