### ISSUE TITLE
No outline when VSCode is opened with ABL code already in editor.

### ISSUE THREAD

**Issue by M0rr155** [vscode-abl/vscode-abl#185] opened 2024-09-05 08:47 UTC

**Comment by M0rr155** [comment] 2024-09-05 08:50
When i start VSCode en ABL code is already (pinned)  in editor, then no outline is showed.
When closing the ABL code en re-open the outline is showing again.

**Comment by gquerret** [comment] 2024-09-09 15:45
Using version 1.11.0 ? That's supposed to be fixed in 1.10.0 (and thus also in 1.11.0)

**Comment by M0rr155** [comment] 2024-09-10 10:27
The extension says: V1.11.1 (pre-release)

________________________________
Van: Gilles Querret ***@***.***>
Verzonden: maandag 9 september 2024 17:46
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] No outline when VSCode is opened with ABL code already in editor. (Issue #185)


Using version 1.11.0 ? That's supposed to be fixed in 1.10.0 (and thus also in 1.11.0)

**Comment by M0rr155** [comment] 2024-09-10 10:30
V1.11.1 (pre-release) and closing / reopening solves it: then outline is shown


Maurice
________________________________
Van: Maurice Stassen | WICS ***@***.***>
Verzonden: dinsdag 10 september 2024 12:26
Aan: vscode-abl/vscode-abl ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] No outline when VSCode is opened with ABL code already in editor. (Issue #185)

The extension says: V1.11.1 (pre-release)

________________________________
Van: Gilles Querret ***@***.***>
Verzonden: maandag 9 september 2024 17:46
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] No outline when VSCode is opened with ABL code already in editor. (Issue #185)


Using version 1.11.0 ? That's supposed to be fixed in 1.10.0 (and thus also in 1.11.0)

**Closed** 2024-09-10 12:56 UTC
Labels: Language Server

**Comment by M0rr155** [comment] 2024-09-11 06:24
Completed?
Is it solved?


________________________________
Van: Gilles Querret ***@***.***>
Verzonden: dinsdag 10 september 2024 14:57
Aan: vscode-abl/vscode-abl ***@***.***>
CC: Maurice Stassen | WICS ***@***.***>; Author ***@***.***>
Onderwerp: Re: [vscode-abl/vscode-abl] No outline when VSCode is opened with ABL code already in editor. (Issue #185)


Closed #185<https://github.com/vscode-abl/vscode-abl/issues/185> as completed.

**Comment by M0rr155** [comment] 2024-09-12 12:18
It is also not working correct in version 1.10.0

**Comment by gquerret** [comment] 2024-09-12 14:01
I can't reproduce locally. Can you enable `Lang server trace` in the settings, restart VS Code with a .p already opened, then close VS Code, and send `%TEMP%\vscode-language-server-trace.txt` ? That will contain all requests / responses, you can upload to https://upload.rssw.eu.

**Comment by M0rr155** [comment] 2024-09-13 06:42
I attached the trace file.

And just to let you see here some screen dumps:
When opened:
![image](https://github.com/user-attachments/assets/deca02a1-4d02-4d8a-9675-d847743740d6)
After closing VSCode en start VSCode again:
![image](https://github.com/user-attachments/assets/1fd13dd1-900a-4ff2-addb-47d86f6b04bd)

[vscode-language-server-trace.txt](https://github.com/user-attachments/files/16989580/vscode-language-server-trace.txt)

**Comment by M0rr155** [comment] 2024-09-13 06:42
[vscode-language-server-trace.txt](https://github.com/user-attachments/files/16989584/vscode-language-server-trace.txt)

**Comment by gquerret** [comment] 2024-09-13 11:22
In your screenshot, the outline view is collapsed, but it's present. And it's visible in the trace. Do you mean that it should be expanded ?

**Comment by PeterJudgeZA** [comment] 2024-09-13 11:26
You can control the auto-open behaviour in the settings. VSCode does respect this setting (and so does the ABL extension))

![image](https://github.com/user-attachments/assets/9464254a-c72c-4b04-90a7-e809085b2caa)

**Comment by M0rr155** [comment] 2024-09-13 11:47
I sent the wrong screendump (sorry for that):

After opening VSCode again, there is no outline:

![image](https://github.com/user-attachments/assets/6aef4e89-d1ce-422d-8ab1-7a745c5f02f4)


i re-attached the trace again:
[vscode-language-server-trace.txt](https://github.com/user-attachments/files/16993321/vscode-language-server-trace.txt)
