### ISSUE TITLE
Syntax coloring

### ISSUE THREAD

**Issue by M0rr155** [vscode-abl/vscode-abl#160] opened 2024-07-11 14:04 UTC
What is the best VS Code coloring theme for Progress ABL language?
I tried a few but they did not come close to the coloring i was used to ...

**Comment by gquerret** [comment] 2024-07-11 14:18
There's no "best" coloring theme, it's just a matter of taste 🙂 

You can customize the colors yourself: [https://code.visualstudio.com/docs/getstarted/themes#\_editor-syntax-highlighting](https://code.visualstudio.com/docs/getstarted/themes#\_editor-syntax-highlighting)

**Comment by danielbecroft** [comment] 2024-07-15 00:16
Agree, it's definitely a matter of taste :-)

One thing that I have found, is that the "keyword" and "datatype" colouring can make quite a difference. For example, using the default "Dark Modern" theme, everything in the ABL starts to be highlighted the same (including the field names of the temp-table, which doesn't make sense). The buffer names are coloured as keywords in the definitions, but not in the CREATE statement, etc.

![image](https://github.com/user-attachments/assets/90ed45f3-f0ec-4771-8d38-55ad3cba7055)

But using something like Material Ocean:

![image](https://github.com/user-attachments/assets/15ab695b-3768-45b4-9615-9899f27c2299)

Here, the buffer / dataset names are coloured the same in the definitions and the usage.

I don't know if this is something related to how the vscode-abl plugin / Language Server is reporting the tokens (which it might be, since the `create ttCustomer`, and `buffer ttCustomer:` highlights the `ttCustomer` token differently, but it is one of the main items that influenced my choice of theme.

**Comment by PeterJudgeZA** [comment] 2024-07-15 00:49
> I don't know if this is something related to how the vscode-abl plugin / Language Server is reporting the tokens (which it might be, since the create ttCustomer, and buffer ttCustomer: highlights the ttCustomer token differently, but it is one of the main items that influenced my choice of theme.

The [abl-tmlanguage](https://github.com/chriscamicas/abl-tmlanguage/) does the syntax highlighting. This is not context sensitive at all, so it cannot differentiate between (say) variables in a method and the parameters in certain circumstances.  Or table.field from package.type similarly.

It can be hard to tell from the colour highlighting, since various themes colour the different tokens differently. There is  the _Developer: Inspect Editor Tokens and Scopes_ function in VSCode that can help identify bad scoping / tokens. If the tokens are incorrect/unexpected feel free to log a bug here (or in that project, but this seems more sensible to me). The expected tokens are listed [here](https://github.com/chriscamicas/abl-tmlanguage/blob/master/README.md) . 

And there are definitely a variety of ~bugs~ unexpected behaviours ...

**Comment by danielbecroft** [comment] 2024-07-15 05:23
Thanks @PeterJudgeZA , I'll keep an eye on that and see if anything is immediately obvious.

**Comment by gquerret** [comment] 2024-07-21 06:31
Closing for now, please open new issues for specific color issues

**Closed by gquerret** 2024-07-21 06:31 UTC

**Comment by M0rr155** [comment] 2024-08-08 12:11
Having some time left, I still do not understand the coloring.
I have added a file where you can see my problem(s):
- CAN-FIND is not the same color as FIND
- FIRST, WHERE, AND, AVAILABLE are all OpenEdge keywords but not colored the same as IF, CASE, WHEN, THEN, DO...

Am I the only one that is a bit lost here?

![VSCode-SyntaxColoring](https://github.com/user-attachments/assets/9824484b-1470-4562-8e7b-54c1e080e04d)

![image](https://github.com/user-attachments/assets/39cedf31-747d-46fb-a482-03590a0e0372)
